dist: bionic
language: elixir
elixir:
  - 1.10
  - 1.9
otp_release:
  - 22.3
  - 21.2 # 21.3 no longer available on Travis
services:
  - redis-server
  - postgresql
  - mysql
before_script:
  - MIX_ENV=test PERSISTENCE=ecto RDBMS=postgres mix compile --warnings-as-errors
  - MIX_ENV=test PERSISTENCE=ecto RDBMS=postgres mix do ecto.create, ecto.migrate
  - rm -rf _build/test/lib/fun_with_flags
  - MIX_ENV=test PERSISTENCE=ecto RDBMS=mysql mix compile --warnings-as-errors
  - MIX_ENV=test PERSISTENCE=ecto RDBMS=mysql mix do ecto.create, ecto.migrate
  - rm -rf _build/test/lib/fun_with_flags
script:
  - mix test.all
notifications:
  email:
    on_success: never
    on_failure: never
cache:
  directories:
    - _build
    - deps
